---
version: '3.6'
services:
  # Setup Elasticsearch
  #   * keystore
  #   * SSL
  setup_elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${TAG}
    container_name: setup_elasticsearch
    command: ['/bin/bash', '-c', 'cat /usr/local/bin/setup-elasticsearch.sh | tr -d "\r" | bash']
    environment: ['ELASTIC_PASSWORD=${ELASTIC_PASSWORD}']
    working_dir: '/config'
    volumes:
      - './config:/config'
      - './scripts/setup-elasticsearch.sh:/usr/local/bin/setup-elasticsearch.sh:ro'

  setup_kibana:
    image: docker.elastic.co/kibana/kibana:${TAG}
    container_name: setup_kibana
    command: ['/bin/bash', '-c', 'cat /usr/local/bin/setup-kibana.sh | tr -d "\r" | bash']
    environment: ['ELASTIC_PASSWORD=${ELASTIC_PASSWORD}']
    working_dir: '/config'
    volumes:
      - './config:/config'
      - './scripts/setup-kibana.sh:/usr/local/bin/setup-kibana.sh:ro'
      - './config/ssl/ca/ca.crt:/usr/share/kibana/config/ca/ca.crt'
    depends_on: ['elasticsearch']
    networks: ['stack']

  setup_logstash:
    image: docker.elastic.co/logstash/logstash:${TAG}
    container_name: setup_logstash
    command: ['/bin/bash', '-c', 'cat /usr/local/bin/setup-logstash.sh | tr -d "\r" | bash']
    environment: ['ELASTIC_PASSWORD=${ELASTIC_PASSWORD}']
    working_dir: '/config'
    volumes:
      - './config:/config'
      - './scripts/setup-logstash.sh:/usr/local/bin/setup-logstash.sh:ro'
      - './config/ssl/ca/ca.crt:/usr/share/logstash/config/ca/ca.crt'
    depends_on: ['elasticsearch']
    networks: ['stack']

  setup_filebeat:
    image: docker.elastic.co/beats/filebeat:${TAG}
    container_name: setup_filebeat
    user: root
    volumes:
      - './config:/config'
      - './scripts/setup-beat.sh:/usr/local/bin/setup-beat.sh:ro'
      - './config/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml'
      - './config/ssl/ca/ca.crt:/usr/share/filebeat/certs/ca/ca.crt'
    command: ['/bin/bash', '-c', 'cat /usr/local/bin/setup-beat.sh | tr -d "\r" | bash -s filebeat']
    environment: ['ELASTIC_PASSWORD=${ELASTIC_PASSWORD}']
    networks: ['stack']
    depends_on: ['kibana']

  setup_redis:
    image: redis
    container_name: setup_redis
    user: root
    networks: ['stack']

  setup_mongo:
    image: mongo
    container_name: setup_mongo
    networks: ['stack']
    user: root
